---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
  strategy: free
  become: yes
  roles:
    - bodsch.snapd
    - common
    - workstation

- hosts: computenodes
  become: yes
  roles:
    - bodsch.snapd
    - common
  vars_files:
    - vars/slurm.yml

- hosts: servers
  become: yes
  roles:
    - common
  vars_files:
    - vars/slurm.yml
