---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
    - vars/netdata.yml
  strategy: free
  become: yes
  roles:
    - bodsch.snapd
    - common
    - workstation

- hosts: computenodes
  become: yes
  roles:
    - bodsch.snapd
    - common
