---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
  strategy: free
  become: yes
  roles:
    - common
    - workstation

- hosts: nvidia
  become: yes
  roles:
    - nvidia

- hosts: computenodes
  become: yes
  roles:
    - common
