- hosts: 
  - workstations
  - computenodes
  become: yes
  tasks:
   - name: update apt-get cache
     apt: update_cache=yes cache_valid_time=3600
     ignore_errors: yes
#   - name: dist-upgrade
#     apt: upgrade=dist  cache_valid_time=3600 autoclean=yes autoremove=yes
   - name: safe-upgrade
     apt: upgrade=safe  cache_valid_time=3600 autoclean=yes autoremove=yes
   - name: update drivedb
     command: wget https://www.smartmontools.org/export/4894/branches/RELEASE_6_2_DRIVEDB/smartmontools/drivedb.h -O /var/lib/smartmontools/drivedb/drivedb.h
   - name: update-pciids
     command: update-pciids
   - name: update-usbids
     command: update-usbids
   - name: update-initram-fs
     command: update-initramfs -k all -c
   - name: update-grub
     command: update-grub
   - name: purge configs
     shell: "dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge"
     ignore_errors: yes
