- hosts: 
  - workstations
  - computenodes
  become: yes
  tasks:
   - name: update apt-get cache
     apt: update_cache=yes
     ignore_errors: yes
 #  - name: Auto-detect and install latest nvidia driver
 #    command: ubuntu-drivers install
   - name: safe-upgrade
     apt: upgrade=safe  cache_valid_time=3600 autoclean=yes autoremove=yes
   - name: dist-upgrade
     apt: upgrade=dist  cache_valid_time=3600 autoclean=yes autoremove=yes
   - name: update-pciids
     command: update-pciids
   - name: update-initram-fs
     command: update-initramfs -k all -c
   - name: update-grub
     command: update-grub
   - name: purge configs
     shell: "dpkg -l | grep '^rc' | awk '{print $2}' | xargs --no-run-if-empty dpkg --purge"
     ignore_errors: yes
