---
- hosts: workstations
  sudo: yes
  tasks:
   - name: install proxy client
     apt: pkg=squid-deb-proxy-client state=latest
   - name: sudo without password
     lineinfile: dest=/etc/sudoers state=present regexp='^%sudo ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
   - name: install keys
     authorized_key: user=localadmin key="{{ lookup('file', '/home/ace/.ssh/id_rsa.pub') }}"
   - name: update apt-get cache
     apt: update_cache=yes
   - name: dist-upgrade
     apt: upgrade=dist
