- name: configure gridengine exec
  lineinfile: dest=/var/lib/gridengine/default/common/act_qmaster 
              regexp='.*' 
              line="cicus01.douglas.rtss.qc.ca" create=yes
  notify: restart gridengine-exec

- name: install
  apt: pkg={{ item }} state=latest
  with_items:
    - gridengine-client
    - gridengine-exec
    - gridengine-qmon
  
- name: ensure execd daemon is running
  service: name=gridengine-exec state=restarted

- name: set complex_values limit
  shell: "qconf -rattr exechost complex_values slots={{ ansible_processor_cores }},num_proc={{ ansible_processor_vcpus }},h_vmem={{ ansible_swaptotal_mb + ansible_memtotal_mb }} {{ansible_fqdn}}"
