- name: config apcupsd.conf
  copy: src=files/apcupsd.conf dest=/etc/apcupsd/apcupsd.conf
  notify:
    - restart apcupsd

- name: config apcupsd
  copy: src=files/apcupsd dest=/etc/default/apcupsd
  notify:
    - restart apcupsd

- name: disable cups-browsed
  service: name=cups-browsed enabled=no state=stopped


- name: Install printer
  command: lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -E -L "CIC 2nd Floor Lobby" -m kyocera/Kyocera_TASKalfa_3253ci.ppd -v socket://10.116.134.16:9100 -o "Option17=DF7120" -o "Option19=One"
  args:
    creates: /etc/cups/ppd/Kyocera-Mita-TASKalfa-3253ci-KPDL.ppd

- name: Set printer defaults
  command: lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -o print-color-mode-default=color -o print-color-mode=color

- name: Set default printer
  command: lpadmin -d Kyocera-Mita-TASKalfa-3253ci-KPDL

#lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -E -L "CIC 2nd Floor Lobby" -m kyocera/Kyocera_TASKalfa_3253ci.ppd -v socket://10.116.134.16:9100 -o "Option17=DF7120" -o "Option19=One"
#lpadmin -d Kyocera-Mita-TASKalfa-3253ci-KPDL
#lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -o print-color-mode-default=color

- name: create sddm config dir
  file:
    path: /etc/sddm.conf.d
    state: directory

- name: copy sddm config to enable graphical logins
  copy: src=files/sddm_local dest=/etc/sddm.conf.d

- name: make plasma default
  file:
    src: /usr/share/xsessions/plasma.desktop
    dest: /usr/share/xsessions/0plasma.desktop
    state: link

- name: Fix kcheckpass
  file:
    path: /usr/lib/x86_64-linux-gnu/libexec/kcheckpass
    mode: u+s

- name: Flush handlers
  meta: flush_handlers
