- name: fix apt http pipeline depth (so it doesn't break squid)
  copy: src=files/99depth dest=/etc/apt/apt.conf.d

- name: install proxy client
  apt: pkg=squid-deb-proxy-client state=latest update_cache=yes

- name: repos enabled
  apt_repository: repo='{{ item }}' state=present update_cache=no
  with_items:
    - ppa:libreoffice/ppa
    - deb http://download.mendeley.com/apt/ stable main
    - ppa:ubuntu-x-swat/x-updates
    - ppa:xorg-edgers/ppa
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - ppa:inkscape.dev/stable
    - ppa:otto-kesselgulasch/gimp
    - ppa:blahota/texstudio
    - deb http://dl.google.com/linux/talkplugin/deb/ stable main
    - deb http://download.virtualbox.org/virtualbox/debian trusty contrib
    - deb http://archive.canonical.com/ubuntu/ trusty partner
    - deb http://dl.google.com/linux/talkplugin/deb/ stable main
    - ppa:ansible/ansible

- name: apt keys
  apt_key: id={{ item }} keyserver=keyserver.ubuntu.com state=present
  with_items:
    - 6F036044
    - 7FAC5991
    - 98AB5139

- name: restrict xorg-edgers
  copy: src=files/xorg-edgers-pin-400 dest=/etc/apt/preferences.d/xorg-edgers-pin-400

- name: software installed
  apt:  pkg={{ item }} state=latest update_cache=yes
  with_items:
    - screen
    - tmux
    - intel-microcode
    - synaptic
    - git
    - cvs
    - subversion
    - google-talkplugin
    - skype
    - imagej
    - speedcrunch
    - openssh-server
    - build-essential
    - mendeleydesktop
    - google-chrome-stable
    - texlive-full
    - inkscape
    - gimp
    - environment-modules
    - vim
    - emacs
    - parallel
    - htop
    - mutt
    - abook
    - nvidia-343
    - virtualbox-4.3
    - xfce4-whiskermenu-plugin
    - xfswitch-plugin
    - axel
    - zip
    - rar
    - unrar
    - unace
    - gnuplot-qt
    - gle-graphics
    - firefox
    - octave
    - iotop
    - ubuntu-restricted-extras
    - texstudio
    - gparted
    - libreoffice
    - ansible
    - thunderbird
    - vlc
    - gnome-terminal
    - cmake
    
- name: hide login list and allow username input
  copy: src=files/99-logins.conf dest=/etc/lightdm/lightdm.conf.d
