- name: install proxy client
  apt: pkg=squid-deb-proxy-client state=latest 

- name: software installed
  apt:  pkg={{ item }} state=present update_cache=yes
  with_items:
    - unattended-upgrades
    - screen
    - tmux
    - intel-microcode
    - git
    - cvs
    - subversion
    - environment-modules
    - htop
    - mutt
    - abook
    - octave
    - iotop
    - ubuntu-restricted-extras
    - texstudio
    - gparted
    - libreoffice
    - libreoffice-help-en-us
    - gnome-terminal
    - numlockx
    - gfortran
    - dcmtk
    - python-pip
    - libapparmor1
    - python-dev
    - libsqlite3-dev
    - sqlite3
    - quota
    - thermald
    - nvidia-cuda-toolkit
    - protobuf-c-compiler
    - protobuf-compiler
    - python-protobuf
    - libssl0.9.8
#fsl-complete expect for fsl-core
    - fsl-atlases
    - fsl-bangor-cerebellar-atlas
    - fsl-first-data
    - fsl-harvard-oxford-atlases
    - fsl-harvard-oxford-cortical-lateralized-atlas
    - fsl-jhu-dti-whitematter-atlas
    - fsl-juelich-histological-atlas
    - fsl-mni-structural-atlas
    - fsl-mni152-templates
    - fsl-oxford-striatal-atlas
    - fsl-oxford-thalamic-connectivity-atlas
    - fsl-possum-data
    - fsl-resting-connectivity-parcellation-atlases
    - fsl-subthalamic-nucleus-atlas
    - fsl-talairach-daemon-atlas
    - fslview
    - fslview-doc
    - libcr0
    - libgdchart-gd2-noxpm
    - libgiftiio0
    - libhwloc-plugins
    - libhwloc5
    - libibverbs1
    - libnetcdfc++4
    - libnetcdfc7
    - libnewmat10ldbl
    - libnifti2
    - libopenmpi1.6
    - libpq5
    - libqt4-designer
    - libqt4-qt3support
    - libqwt5-qt4
    - libtorque2
    - libvtk5.8
    - libvtk5.8-qt4
    - qt-assistant-compat
    - tcsh
    - g++
    - cmake
    - cmake-curses-gui
    - bison
    - flex
    - freeglut3
    - freeglut3-dev
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
#R build deps
    - gfortran
    - libreadline-dev
    - libcairo-dev
    - openjdk-7-jdk
#CIVET build deps
    - automake
    - autoconf
    - libtool
    - libblas-dev
    - liblapack-dev
    - libnetpbm10-dev
#Brain-view2
    - libpcre++0

- name: install pip software
  pip: name={{ item }} state=latest
  with_items:
    - reprozip
    - reprounzip

