- name: fix apt http pipeline depth (so it doesn't break squid)
  copy: src=files/99depth dest=/etc/apt/apt.conf.d

- name: install proxy client
  apt: pkg=squid-deb-proxy-client state=latest 

- name: repos enabled
  apt_repository: repo='{{item}}' state=present update_cache=no
  with_items:
    - ppa:libreoffice/ppa
    - deb http://download.mendeley.com/apt/ stable main
    - ppa:ubuntu-x-swat/x-updates
    - ppa:xorg-edgers/ppa
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - ppa:inkscape.dev/stable
    - ppa:otto-kesselgulasch/gimp
    - ppa:blahota/texstudio
    - deb http://dl.google.com/linux/talkplugin/deb/ stable main
    - deb http://download.virtualbox.org/virtualbox/debian trusty contrib
    - deb http://archive.canonical.com/ubuntu/ trusty partner
    - deb http://dl.google.com/linux/talkplugin/deb/ stable main
    - ppa:ansible/ansible
    - deb http://neuro.debian.net/debian data main contrib non-free
    - deb http://neuro.debian.net/debian trusty main contrib non-free

- name: apt keys
  apt_key: id={{ item }} keyserver=keyserver.ubuntu.com state=present
  with_items:
    - 6F036044
    - 7FAC5991
    - 98AB5139
    - 2649A5A9

- name: restrict xorg-edgers
  copy: src=files/xorg-edgers-pin-400 dest=/etc/apt/preferences.d/xorg-edgers-pin-400

- name: software installed
  apt:  pkg={{ item }} state=present update_cache=yes
  with_items:
    - unattended-upgrades
    - screen
    - tmux
    - intel-microcode
    - synaptic
    - git
    - cvs
    - subversion
    - google-talkplugin
    - skype
    - imagej
    - imagemagick
    - speedcrunch
    - openssh-server
    - build-essential
    - mendeleydesktop
    - google-chrome-stable
    - texlive-full
    - inkscape
    - gimp
    - environment-modules
    - vim
    - emacs
    - parallel
    - htop
    - mutt
    - abook
    - nvidia-343
    - nvidia-343-uvm
    - nvidia-343-dev
    - nvidia-opencl-icd-343
    - virtualbox-4.3
    - axel
    - zip
    - rar
    - unrar
    - unace
    - gnuplot-qt
    - gle-graphics
    - firefox
    - octave
    - iotop
    - ubuntu-restricted-extras
    - texstudio
    - gparted
    - libreoffice
    - libreoffice-help-en-us
    - ansible
    - thunderbird
    - vlc
    - gnome-terminal
    - numlockx
    - gfortran
    - dcmtk
    - python-pip
    - libapparmor1
    - python-dev
    - libsqlite3-dev
    - sqlite3
    - pspp
    - nedit
    - quota
    - thermald
    - nvidia-cuda-toolkit
    - protobuf-c-compiler
    - protobuf-compiler
    - python-protobuf
    - libssl0.9.8
#fsl-complete expect for fsl-core
    - fsl-atlases
    - fsl-bangor-cerebellar-atlas
    - fsl-first-data
    - fsl-harvard-oxford-atlases
    - fsl-harvard-oxford-cortical-lateralized-atlas
    - fsl-jhu-dti-whitematter-atlas
    - fsl-juelich-histological-atlas
    - fsl-mni-structural-atlas
    - fsl-mni152-templates
    - fsl-oxford-striatal-atlas
    - fsl-oxford-thalamic-connectivity-atlas
    - fsl-possum-data
    - fsl-resting-connectivity-parcellation-atlases
    - fsl-subthalamic-nucleus-atlas
    - fsl-talairach-daemon-atlas
    - fslview
    - fslview-doc
    - libcr0
    - libgdchart-gd2-noxpm
    - libgiftiio0
    - libhwloc-plugins
    - libhwloc5
    - libibverbs1
    - libnetcdfc++4
    - libnetcdfc7
    - libnewmat10ldbl
    - libnifti2
    - libopenmpi1.6
    - libpq5
    - libqt4-designer
    - libqt4-qt3support
    - libqwt5-qt4
    - libtorque2
    - libvtk5.8
    - libvtk5.8-qt4
    - qt-assistant-compat
    - tcsh
    - g++
    - cmake
    - cmake-curses-gui
    - bison
    - flex
    - freeglut3
    - freeglut3-dev
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
#R build deps
    - gfortran
    - libreadline-dev
    - libcairo-dev
    - openjdk-7-jdk
#CIVET build deps
    - automake
    - autoconf
    - libtool
    - libblas-dev
    - liblapack-dev
    - libnetpbm10-dev
#Brain-view2
    - libpcre++0

- name: install pip software
  pip: name={{ item }} state=latest
  with_items:
    - reprozip
    - reprounzip

- name: configure lightdm login
  copy: src=files/99-logins.conf dest=/etc/lightdm/lightdm.conf.d

- name: configure adblock chrome
  copy: src=files/cjpalhdlnbpafiamejdnhcphjbkeiagm.json dest=/usr/share/google-chrome/extensions/

- name: fix powerkey
  lineinfile: dest=/etc/systemd/logind.conf line=HandlePowerKey=ignore

- name: disable apport
  lineinfile: dest=/etc/default/apport regexp=^enabled= line=enabled=0
