- name: install debs
  apt: deb={{ item }}
  with_items:
    - https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    - https://zoom.us/client/latest/zoom_amd64.deb
    - https://github.com/usebruno/bruno/releases/download/v1.4.0/bruno_1.4.0_amd64_linux.deb
  ignore_errors: yes
