- name: Install workstation apt packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - firefox-esr
      - meld
      - brave-browser
      - gnuplot-qt
      - yubikey-manager
      - yubikey-personalization-gui
      - libpam-yubico
      - libpam-u2f
      - yubioath-desktop
      - texlive-full
      - x2goserver
      - x2goclient
      - x2goserver-xsession
      - partitionmanager
      - language-pack-en
      - language-pack-fr
      - language-pack-gnome-en
      - language-pack-gnome-fr
      - gimp-help-en
      - gimp-help-fr
      - feh
      - xfig
      - lxqt-core
      - lxde-core
      - google-chrome-stable
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-fr
      - libreoffice
      - libreoffice-style-breeze
      - krita
      - kdenlive
      - kolourpaint
      - flatpak
      - default-jre
      - firefox
      - kubuntu-restricted-addons
      - kubuntu-restricted-extras
      - obs-studio
      - speedcrunch
      - aeskulap
      - flameshot
      - peek
      # Globus connect personal
      - tk
      - tcllib
      # VMWARE Connect
      - libudev0
      - flameshot
      - dconf-editor
      - pspp
      - sassc
      - autokey-gtk

- name: remove problematic software
  apt: pkg={{ item }} state=absent update_cache=yes cache_valid_time=3600
  with_items:
    - ktorrent

- name: Install kernel and nvidia and hold
  ansible.builtin.script: bin/install_kernel.sh

- name: default firefox for browser
  community.general.alternatives:
    name: x-www-browser
    path: /usr/bin/firefox
