 - name: dist-upgrade
   apt: upgrade=dist update_cache=yes autoclean=yes autoremove=yes

- name: Install workstation apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
  vars:
    packages:
      - texlive-full
      - x2goserver
      - x2goclient
      - x2goserver-xsession
      - partitionmanager
      - language-pack-en
      - language-pack-fr
      - language-pack-de
      - feh
      - xfig
      - meshlab
      - lxqt-core
      - google-chrome-stable
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-fr
      - libreoffice
      - libreoffice-style-breeze
      - inkscape
      - gimp
      - vlc
      - flatpak
      - default-jre
      - firefox
      - kubuntu-restricted-addons
      - kubuntu-restricted-extras

- name: remove problematic software
  apt:  pkg={{ item }} state=absent update_cache=yes cache_valid_time=3600
  with_items:
    - ktorrent

- name: Auto-detect and install latest nvidia driver
  command:  ubuntu-drivers install

- name: Enable flatpak repo
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
