- name: Download kyocerya driver
  unarchive:
    src: https://www.kyoceradocumentsolutions.ca/content/download-center-americas/ca/drivers/drivers/KyoceraLinuxPackages_20220203_tar_gz.download.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/Ubuntu/Global/kyodialog_amd64/kyodialog_9.1-0_amd64.deb

- name: install debs
  apt: deb={{ item }}
  with_items:
    - /tmp/Ubuntu/Global/kyodialog_amd64/kyodialog_9.1-0_amd64.deb
  ignore_errors: yes

- name: disable cups-browsed
  service: name=cups-browsed enabled=no state=stopped

- name: Install printer
  command: lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -E -L "CIC 2nd Floor Lobby" -m kyocera/Kyocera_TASKalfa_3253ci.ppd -v socket://10.116.134.16:9100 -o "Option17=DF7120" -o "Option19=One"
  args:
    creates: /etc/cups/ppd/Kyocera-Mita-TASKalfa-3253ci-KPDL.ppd

- name: Set printer defaults
  command: lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -o print-color-mode-default=color -o print-color-mode=color

- name: Set default printer
  command: lpadmin -d Kyocera-Mita-TASKalfa-3253ci-KPDL

#lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -E -L "CIC 2nd Floor Lobby" -m kyocera/Kyocera_TASKalfa_3253ci.ppd -v socket://10.116.134.16:9100 -o "Option17=DF7120" -o "Option19=One"
#lpadmin -d Kyocera-Mita-TASKalfa-3253ci-KPDL
#lpadmin -p Kyocera-Mita-TASKalfa-3253ci-KPDL -o print-color-mode-default=color
