- name: Setup virtualgl
  command: /opt/VirtualGL/bin/vglserver_config +glx -config +s +f +t
  args:
    creates: /etc/modprobe.d/virtualgl.conf
  notify:
    - reboot machine

- name: Properly install xorg config for virtualgl
  ansible.builtin.file:
    src: /etc/X11/xorg.conf.d/99-virtualgl-dri
    dest: /etc/X11/xorg.conf.d/99-virtualgl-dri.conf
    state: link

- name: Enable indirect rendering
  copy: src=files/99-indirect.conf dest=/etc/X11/xorg.conf.d/99-indirect.conf  
