- name: Download VMware Horizon Installer
  unarchive:
    src: https://download3.vmware.com/software/CART23FQ2_LIN_2206_TARBALL/VMware-Horizon-Client-Linux-2206-8.6.0-20094634.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /usr/bin/vmware-view

- name: Unpack VMware Horizon Client
  ansible.builtin.command: tar xzvf /tmp/VMware-Horizon-Client-Linux-2206-8.6.0-20094634/x64/VMware-Horizon-Client-2206-8.6.0-20094634.x64.tar.gz -C /usr --strip-components=1
  args:
    creates: /usr/bin/vmware-view

- name: Unpack VMware Horizon PCoIP
  ansible.builtin.command: tar xzvf /tmp/VMware-Horizon-Client-Linux-2206-8.6.0-20094634/x64/VMware-Horizon-PCoIP-2206-8.6.0-20094634.x64.tar.gz -C /usr --strip-components=1
  args:
    creates: /usr/lib/libpcoip_client.so

- name: config vmware horizon client
  copy: src=files/view-mandatory-config dest=/etc/vmware/
