- name: Fix broken ubuntu-drivers installs
  shell: "apt install -y $(dpkg -l | grep nvidia-driver- | awk '{print $2}' | sed 's/driver/dkms/g')"
  ignore_errors: yes

- name: Install workstation apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
    cache_valid_time: 3600
  vars:
    packages:
      - libcublas11
      - libcufftw10
      - libcufft10
