- name: disable apport
  lineinfile: dest=/etc/default/apport regexp=^enabled= line=enabled=0

- name: enable unattended upgrades
  copy: src=files/50unattended-upgrades dest=/etc/apt/apt.conf.d/

- name: enable periodic upgrades
  copy: src=files/02periodic dest=/etc/apt/apt.conf.d/

- name: config ntpd
  copy: src=files/ntpd.conf dest=/etc/openntpd/ntpd.conf
  notify:
   - restart ntpd

- name: config ntpd defaults
  copy: src=files/openntpd dest=/etc/default/

- name: config network
  copy: src=files/interfaces dest=/etc/network/interfaces

- name: config smartmontools
  copy: src=files/smartmontools dest=/etc/default/smartmontools

- name: config smartd.conf
  copy: src=files/smartd.conf dest=/etc/
  notify:
    - restart smartmontools

- name: config apcupsd.conf
  copy: src=files/apcupsd.conf dest=/etc/apcupsd/apcupsd.conf
  notify:
    - restart apcupsd

- name: config apcupsd
  copy: src=files/apcupsd dest=/etc/default/apcupsd
  notify:
    - restart apcupsd

- name: install ppds
  copy: src={{ item }} dest=/etc/cups/ppd
  with_items:
    - files/Kyocera-Mita-TASKalfa-4551ci-KPDL.ppd

- name: install printer.conf
  copy: src=files/printers.conf dest=/etc/cups
  notify:
    - restart cups
    - restart cups-browsed

- name: install cups-browsed.conf
  copy: src=files/cups-browsed.conf dest=/etc/cups
  notify:
    - restart cups
    - restart cups-browsed

- name: setup ssmtp
  lineinfile: dest=/etc/ssmtp/ssmtp.conf regexp=^root= line=root=root@cicus03

- name: setup mailhub
  lineinfile: dest=/etc/ssmtp/ssmtp.conf regexp=^mailhub= line=mailhub=cicus03

- name: configure logcheck
  copy: src=files/logcheck.conf dest=/etc/logcheck/

- name: ignore ntpd in logcheck
  copy: src=files/ntpd.logcheck dest=/etc/logcheck/ignore.d.workstation/ntpd

- name: ignore ssmtp logcheck
  copy: src=files/ssmtp.logcheck dest=/etc/logcheck/ignore.d.workstation/ssmtp

- name: ignore ansible logcheck
  copy: src=files/ansible.logcheck dest=/etc/logcheck/ignore.d.workstation/ansible

- name: ignore systemd logcheck
  copy: src=files/systemd.logcheck dest=/etc/logcheck/ignore.d.workstation/systemd

- name: ignore colord logcheck
  copy: src=files/colord.logcheck dest=/etc/logcheck/ignore.d.workstation/colord

- name: ignore rtkit logcheck
  copy: src=files/rtkit.logcheck dest=/etc/logcheck/ignore.d.workstation/rtkit

- name: ignore dhclient logcheck
  copy: src=files/dhclient.logcheck dest=/etc/logcheck/ignore.d.workstation/dhclient

- name: ignore avahi
  copy: src=files/avahi.logcheck dest=/etc/logcheck/ignore.d.workstation/avahi

- name: ignore dbus
  copy: src=files/dbus.logcheck dest=/etc/logcheck/ignore.d.workstation/dbus

- name: fix logcheck ownerships
  file: path=/etc/logcheck/ignore.d.workstation state=directory recurse=yes group=logcheck

- name: enable all locales
  file: src=/usr/share/i18n/SUPPORTED dest=/var/lib/locales/supported.d/all state=link

- name: generate all locales
  command: /usr/sbin/locale-gen

- name: Set some kernel parameters
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - net.ipv6.conf.all.disable_ipv6 = 1
    - net.ipv6.conf.default.disable_ipv6 = 1
    - net.ipv6.conf.lo.disable_ipv6 = 1

- name: Set sshd_config
  copy: src=files/sshd_config dest=/etc/ssh

- name: Set ssh_config
  copy: src=files/ssh_config dest=/etc/ssh
