- name: enable sudo with no password for sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%sudo ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- {include: hosts.yml, tags: hosts}
- {include: nis.yml, tags: nis}
- {include: nfs.yml, tags: nfs}
- {include: quarantine.yml, tags: quarantine}
  
- name: enable ssh keys
  authorized_key: user=localadmin key="{{ lookup('file', '/home/ace/.ssh/id_rsa.pub') }}"
