- name: enable ssh keys
  authorized_key: user=localadmin key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#- apt: update_cache=yes

#- name: remove squid-deb-proxy-client
#  apt: pkg=squid-deb-proxy-client state=absent update_cache=no purge=yes

#- apt: upgrade=dist update_cache=yes cache_valid_time=3600

- {include: hosts.yml, tags: hosts}
- {include: nis.yml, tags: nis}
- {include: nfs.yml, tags: nfs}
- {include: quarantine.yml, tags: quarantine}
- {include: repos.yml, tags: software}
- {include: packages.yml, tags: software}
- {include: manual-deb.yml, tags: software}
- {include: file-config.yml, tags: files}

- name: enable sudo with no password for sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%sudo ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: add devgab to sudo group
  lineinfile: dest=/etc/group state=present regexp=^sudo line=sudo:x:27:localadmin,devgab

