  - name: Add condition to skip MOTD messages for non-cicadministrators users
    blockinfile:
      path: /etc/update-motd.d/{{ item }}
      insertafter: '^#!/bin/sh'
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        # If the user is not part of 'cicadministrators', skip the MOTD
        if ! groups | grep -q cicadministrators; then
            exit 0
        fi
    loop:
      - "00-header"
      - "10-help-text"
      - "50-landscape-sysinfo"
      - "50-motd-news"
      - "85-fwupd"
      - "90-updates-available"
      - "91-contract-ua-esm-status"
      - "91-release-upgrade"
      - "92-unattended-upgrades"
      - "95-hwe-eol"
      - "98-fsck-at-reboot"
      - "98-reboot-required"

  - name: Copy 99-dnp-ssh-welcome to /etc/update-motd.d
    copy:
      src: files/motd/99-dnp-ssh-welcome
      dest: /etc/update-motd.d/99-dnp-ssh-welcome
      mode: 'u=rwx,g=rx,o=rx'

  - name: Remove legal warning
    ansible.builtin.file:
      state: absent
      path: /etc/legal
