- name: nfs-common installed
  apt:  pkg=nfs-common state=latest

- name: autofs installed
  apt: pkg=autofs state=latest

- name: create /opt/quarantine
  file: path=/opt/quarantine state=directory

- name: quarantine fstab
  mount: src="cicss01:/quarantine" name=/opt/quarantine fstype=nfs4  opts="vers=4,rw,nodev,hard,intr,hard,intr,sloppy,async,_netdev"  state=mounted
  
- name: create place for homdirs
  file: path=/home/cic state=directory

- name: mount homedirs
  mount: src="cicus01:/users" name=/home/cic fstype=nfs opts="rw,nodev,hard,intr,hard,intr,sloppy,async,_netdev" state=mounted

- name : setup auto.master
  copy: src=files/auto.master dest=/etc/auto.master
  notify: restart autofs
  
- name: create /data
  file: path=/data state=directory

- name: autofs /data
  copy: src=files/auto.data dest=/etc/auto.data
  notify: restart autofs

- name: create /backup
  file: path=/backup state=directory

- name: autofs /backup
  copy: src=files/auto.backup dest=/etc/auto.backup
  notify: restart autofs

- name: configure nfs-common
  copy: src=files/nfs-common dest=/etc/default/nfs-common
