- name: nfs-common installed
  apt:  pkg=nfs-common state=present

- name: autofs installed
  apt: pkg=autofs state=present

- name: autofs installed
  apt: pkg=cachefilesd state=absent
  notify: restart autofs

- name: Enable cachefilesd
  ansible.builtin.lineinfile:
    path: /etc/default/cachefilesd
    regexp: '^RUN='
    line: RUN=no
  notify: restart autofs
  ignore_errors: true

- name: create place for homdirs
  file: path=/home/cic state=directory

- name: create autofs directory
  file: path=/etc/auto.master.d state=directory

- name : setup cic.autofs
  copy: src=files/cic.autofs dest=/etc/auto.master.d
  notify: restart autofs

- name: create /data
  file: path=/data state=directory

- name: autofs /data
  copy: src=files/auto.data dest=/etc/auto.data
  notify: restart autofs

- name: create /dicom
  file: path=/dicom state=directory

- name: autofs /home
  copy: src=files/auto.home dest=/etc/auto.home
  notify: restart autofs

- name: autofs direct maps
  copy: src=files/auto.direct  dest=/etc/auto.direct
  notify: restart autofs

- name: configure nfs-common
  copy: src=files/nfs-common dest=/etc/default/nfs-common

- name: optimize dirty_bytes data nfs
  ansible.posix.sysctl:
    name: vm.dirty_bytes
    value: 629145600
    state: present
    reload: yes

- name: optimize dirty_background_bytes data nfs
  ansible.posix.sysctl:
    name: vm.dirty_background_bytes
    value: 314572800
    state: present
    reload: yes

- name: Symlink for DICOMS
  ansible.builtin.file:
    src: /data/dicom/incoming
    dest: /dicom
    owner: root
    group: root
    state: link
    force: yes

- name: Flush handlers
  meta: flush_handlers

