- name: nfs-common installed
  apt:  pkg=nfs-common state=latest

- name: autofs installed
  apt: pkg=autofs state=latest

- name: cachefilesd installed
  apt: pkg=cachefilesd state=latest

- name: config cachefilesd
  copy: src=files/cachefilesd dest=/etc/default/

- name: create place for homdirs
  file: path=/home/cic state=directory

- name: mount homedirs
  mount: src="cicus03:/tank/users" name=/home/cic fstype=nfs4 opts="v4.1,rw,nodev,hard,intr,sloppy,async,fsc,noatime,nodiratime,noauto" state=mounted

- name: quarantine fstab
  mount: src="cicss03:/data/quarantine" name=/opt/quarantine fstype=nfs4  opts="v4.1,rw,nodev,hard,intr,sloppy,async,fsc,noatime,nodiratime,noauto" state=mounted

- name : setup auto.master
  copy: src=files/auto.master dest=/etc/auto.master
  notify: restart autofs

- name: create /data
  file: path=/data state=directory

- name: autofs /data
  copy: src=files/auto.data dest=/etc/auto.data
  notify: restart autofs

- name: create /backup
  file: path=/backup state=directory

- name: autofs /backup
  copy: src=files/auto.backup dest=/etc/auto.backup
  notify: restart autofs

- name: configure nfs-common
  copy: src=files/nfs-common dest=/etc/default/nfs-common

- name: fix nfs on boot
  copy: src=files/rc.local dest=/etc/rc.local

- name: fix nfs on boot again
  copy: src=files/mount_netdev.sh dest=/etc/init.d/mount_netdev.sh mode="u=rwx,g=rx,o=rx"

- name: enable service nfs fix service
  command: /bin/ln -s /etc/init.d/mount_netdev.sh /etc/rcS.d/S99mount_netdev.sh creates=/etc/rcS.d/S99mount_netdev.sh
