- name: set defaultdomain
  copy: src=files/defaultdomain dest=/etc/defaultdomain
  notify:
    - restart rpcbind 
    - restart ypbind
  
- name: set ypservers
  copy: src=files/yp.conf dest=/etc/yp.conf
  notify: 
    - restart rpcbind
    - restart ypbind

- name: nis installed
  apt: pkg={{ item }} state=latest
  with_items:
    - nis
    - rpcbind
    - nscd
  notify:
    - restart rpcbind
    - restart ypbind
  
- name: set nsswitch
  copy: src=files/nsswitch.conf dest=/etc/nsswitch.conf

- name: automatic nss restart
  when_changed: $last_task
  service: name={{ item }} state=restarted
  with_items:
    - rpcbind
    - ypbind
