- apt: upgrade=dist update_cache=yes cache_valid_time=3600

- name: install proxy client
  apt: pkg=squid-deb-proxy-client state=latest update_cache=no

- name: accept oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install common packages
  apt:  pkg={{ item }} state=latest update_cache=no
  with_items:
    - python-pip
    - pv
    - openntpd
    - xauth
    - lm-sensors
    - thermald
    - tmux
    - screen
    - apcupsd
    - landscape-common
    - ssmtp
    - unattended-upgrades
    - lvm2
    - exfat-utils
    - graphicsmagick-imagemagick-compat
    - ubuntu-zfs
    - irssi
    - openssh-server
    - ansible
    - environment-modules
    - quota
    - parallel
    - cvs
    - subversion
    - ruby
    - ruby-dev
    - make
    - gcc
    - nodejs
    - build-essential
    - gfortran
    - git
    - aptitude
    - intel-microcode
    - libnss-myhostname
    - nmap
    - oracle-java7-installer
    - lrzip
    - htop
    - iotop
    - p7zip-rar
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi
    - dkms
    - python-numpy
    - python-scipy
    - python-matplotlib
    - ipython
    - ipython-notebook
    - python-pandas
    - python-sympy
    - python-nose
    - python-scitools
    - vim
    - exuberant-ctags
    - vim-doc
    - vim-scripts
    - fonts-inconsolata
    - octave
    - pspp
    - emacs
    - git
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - ntfs-3g
    - dosfstools
    - dmraid
    - dmsetup
    - kpartx
    - freeipmi
    - automake
    - autoconf
    - libtool
    - debconf-utils
    - logcheck
    - syslog-summary
    - pam-kwallet
    - apparmor-profiles
#libraries
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - cmake
    - cmake-curses-gui
    - protobuf-c-compiler
    - protobuf-compiler
    - python-protobuf
    - netcdf-bin
    - libnetcdf-dev
    - libnetcdfc7
    - libnetcdff5
    - libnetcdfc++4
    - libhdf4-0
    - libhdf4-dev
    - libhdf5-7
    - libhdf5-dev
    - lib32gcc1
    - libblas-dev
    - liblapack-dev
    - libnetpbm10-dev
    - libpcre++0
    - bison
    - flex
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
    - libsqlite3-dev
    - libjpeg62
    - liblcms1
    - libperl4-corelibs-perl
    - tcl8.4
    - tcl8.5
    - tk8.4
    - tk8.5
    - libgdchart-gd2-xpm
    - libgiftiio0
    - libnewmat10ldbl
    - libnifti2
    - libqt4-qt3support
    - libqwt5-qt4
    - libvtk5.8-qt4


- name: install github and jekyll suppor
  gem: name={{ item }} state=latest
  with_items:
    - jekyll
    - github-pages

#- name: install pip software
#  pip: name={{ item }} state=latest
#  with_items:
#    - reprozip
#    - reprounzip
