- apt: upgrade=dist update_cache=yes cache_valid_time=3600

- name: Install HWE
  shell: apt install --install-recommends linux-generic-hwe-20.04 -y

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: Install Common APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - ccache
    - watchdog
    - ssmtp
    - htop
    - iotop
    - xauth
    - landscape-common
    - tmux
    - screen
    - apcupsd
    - imagemagick
    - exfat-utils
    - ntfs-3g
    - dosfstools
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - dmraid
    - dmsetup
    - kpartx
    - cryptsetup
    - openssh-server
    - parallel
    - quota
    - nmap
    - lrzip
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - dkms
    - kubuntu-restricted-addons
    - kubuntu-restricted-extras
    - ansible
    - apparmor-profiles-extra
    - apparmor-profiles
    - smartmontools
    - squashfs-tools
    - singularity-container
    - links2
    - aptitude
    - tree
    - unattended-upgrades
    - nvme-cli
#Development software
    - vim
    - emacs
    - build-essential
    - source-highlight
    - cmake
    - cmake-curses-gui
    - gcc
    - gfortran
    - default-jdk
    - git
    - make
    - ninja-build
    - cpanminus
    - libpng12-dev
#Science software
    - environment-modules
    - octave
#Docker
    - docker-ce
    - docker-ce-cli
    - containerd.io
#minc-toolkit-v2 build deps
    - bc
    - bison
    - flex
    - libx11-dev
    - x11proto-core-dev
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libjpeg-dev
    - libssl-dev
    - zlib1g-dev
    - automake
#mrtrix3 dependencies
    - g++
    - python-is-python3
    - libeigen3-dev
    - libqt5opengl5-dev
    - libqt5svg5-dev
    - libfftw3-dev
    - libtiff5-dev
    - libpng-dev
#afni dependencies
    - tcsh
    - xfonts-base
    - python3-matplotlib
    - gsl-bin
    - netpbm
    - libjpeg62
    - xvfb
    - xterm
    - curl
    - libglw1-mesa
    - libxm4
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgfortran-8-dev
    - libgomp1
    - xfonts-100dpi

#- name: Install clang
#  apt:
#    name: "{{ packages }}"
#    update_cache: yes
#    state: latest
#  vars:
#    packages:
#    - clang-12
#    - lldb-12
#    - lld-12
#    - clangd-12

#Fix the lmod package for 18.04
#https://bugs.launchpad.net/ubuntu/+source/lua-posix/+bug/1752082
#- name: fix lua symlink
#  file:
#    src: /usr/lib/x86_64-linux-gnu/lua/5.2/posix_c.so
#    dest: /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so
#    state: link


#Fix afni being built against a different version of gsl
#https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu18.html
- name: fix libgsl
  file:
    src: /usr/lib/x86_64-linux-gnu/libgsl.so.23
    dest: /usr/lib/x86_64-linux-gnu/libgsl.so.19
    state: link

- name: remove problematic software
  apt:  pkg={{ item }} state=absent update_cache=yes cache_valid_time=3600
  with_items:
    - snapd

#Install missing perl package
- cpanm: name="Math::Matrix"
