- name: configure proxy
  copy: src=files/99squid-deb-proxy dest=/etc/apt/apt.conf.d

- apt: upgrade=dist update_cache=yes cache_valid_time=3600

- name: accept oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: accept oracle license
  debconf: name='oracle-java9-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: install common packages
  apt:  pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python-pip
    - pv
    - openntpd
    - xauth
    - lm-sensors
    - thermald
    - tmux
    - screen
    - apcupsd
    - landscape-common
    - ssmtp
    - unattended-upgrades
    - lvm2
    - exfat-utils
    - imagemagick
    - irssi
    - openssh-server
    - ansible
    - environment-modules
    - quota
    - parallel
    - cvs
    - subversion
    - ruby-dev
    - make
    - gcc
    - nodejs
    - build-essential
    - gfortran
    - git
    - aptitude
    - intel-microcode
    - libnss-myhostname
    - nmap
    - oracle-java7-installer
    - oracle-java9-installer
    - oracle-java9-unlimited-jce-policy
    - lrzip
    - htop
    - iotop
    - p7zip-rar
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - dkms
    - python-numpy
    - python-scipy
    - python-matplotlib
    - ipython
    - ipython-notebook
    - python-pandas
    - python-sympy
    - python-nose
    - python-scitools
    - vim
    - exuberant-ctags
    - vim-doc
    - vim-scripts
    - fonts-inconsolata
    - octave
    - pspp
    - emacs
    - git
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - ntfs-3g
    - dosfstools
    - dmraid
    - dmsetup
    - cachefilesd
    - kpartx
    - freeipmi
    - automake
    - autoconf
    - libtool
    - debconf-utils
    - logcheck
    - syslog-summary
    - pam-kwallet
    - python-argcomplete
    - python-optcomplete
#libraries
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - cmake
    - cmake-curses-gui
    - protobuf-c-compiler
    - protobuf-compiler
    - python-protobuf
    - netcdf-bin
    - libnetcdf-dev
    - libnetcdfc7
    - libnetcdff5
    - libnetcdfc++4
    - libhdf4-0
    - libhdf4-dev
    - libhdf5-7
    - libhdf5-dev
    - lib32gcc1
    - libblas-dev
    - liblapack-dev
    - libnetpbm10-dev
    - libpcre++0
    - bison
    - flex
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
    - libsqlite3-dev
    - libjpeg62
    - liblcms1
    - libperl4-corelibs-perl
    - tcl8.4
    - tcl8.5
    - tk8.4
    - tk8.5
    - libgdchart-gd2-xpm
    - libgiftiio0
    - libnewmat10ldbl
    - libnifti2
    - libqt4-qt3support
    - libqwt5-qt4
    - libvtk5.8-qt4
    - libgetopt-tabular-perl
    - libroot-math-matrix-dev
    - libgetopt-argvfile-perl
#torch deps
    - build-essential
    - gcc
    - cmake
    - curl
    - libreadline-dev
    - git
    - libqt4-core
    - libjpeg-dev
    - libpng-dev
    - ncurses-dev
    - libzmq3-dev
    - gfortran
    - unzip
    - gnuplot-qt
    - libsdl2-dev
    - libgraphicsmagick1-dev
    - nodejs
    - npm
    - libfftw3-dev
    - g++
    - libqt4-gui
    - libqt4-dev
    - sox
    - libsox-dev
    - libsox-fmt-all
    - libopenblas-base
    - libopenblas-dev
#opencv
    - libopencv-dev
    - python-opencv
    - libopencv-dev 
    - libgtk2.0-dev
    - pkg-config
    - python-dev 
    - python-numpy 
    - libdc1394-22 
    - libdc1394-22-dev
    - libjpeg-dev
    - libpng12-dev
    - libtiff4-dev
    - libjasper-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libxine-dev
    - libgstreamer0.10-dev
    - libgstreamer-plugins-base0.10-dev
    - libv4l-dev
    - libtbb-dev
    - libqt4-dev
    - libfaac-dev
    - libmp3lame-dev
    - libopencore-amrnb-dev
    - libopencore-amrwb-dev
    - libtheora-dev
    - libvorbis-dev
    - libxvidcore-dev
    - x264
    - v4l-utils 
    - unzip
    - libssl0.9.8
    - libvtk5-dev
    - python-vtk
    - cpanminus
#soge deps
    - db5.1-util
    - libdb5.1
    - libjemalloc1
    - tcsh

- name: remove problematic software
  apt:  pkg={{ item }} state=absent update_cache=yes cache_valid_time=3600
  with_items:
    - apparmor
    - apparmor-profiles

- cpanm: name="Math::Matrix"
