---
- name: Install qbatch with pipx
  shell: 'PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install qbatch'

- name: Install qbatch env var config
  copy: src=files/99qbatch.sh dest=/etc/profile.d/
