- name: quarantine package
  apt: pkg=environment-modules state=latest

- name: copy quarantine profile
  copy: src=files/quarantine.sh dest=/etc/profile.d

- name: enable modules for bash
  lineinfile: dest=/etc/bash.bashrc line="source /etc/profile.d/modules.sh"

- name: enable quarantine
  lineinfile: dest=/etc/bash.bashrc line="source /etc/profile.d/quarantine.sh"

- name: quarantine fstab
  mount:  src="cicss01:/quarantine" name=/opt/quarantine fstype=nfs  opts="vers=4,rw,nodev,hard,intr,hard,intr,sloppy,async"  state=mounted
