- name: Update root user GECOS field for email readability
  ansible.builtin.user:
    name: root
    comment: "root@{{ ansible_facts['nodename'] }}"

- name: configure sudo email address
  lineinfile:
    path: /etc/sudoers.d/99-sudoers-config
    create: yes
    line: "Defaults mailfrom=\"{{ ansible_facts['nodename'] }}@douglas.mcgill.ca\""
    validate: 'visudo -cf %s'

- name: add cicadministrators to sudoers
  lineinfile:
    path: /etc/sudoers.d/99-sudoers-config
    line: "%cicadministrators ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'

- name: Set HISTTIMEFORMAT in global bashrc
  blockinfile:
    path: "/etc/bash.bashrc"
    block: |
      #append date & time stamps
      export HISTTIMEFORMAT="%F %T "
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HISTTIMEFORMAT"
  notify:
    - source global_bashrc

