- name: install gridengine packages
  apt: deb={{ item }}
  with_items:
    - /data/scratch/soge/lesstif2_0.95.2-1_amd64.deb
    - /data/scratch/soge/sge-common_8.1.8_all_fixed.deb
    - /data/scratch/soge/sge_8.1.8_amd64.deb
    - /data/scratch/soge/sge-doc_8.1.8_all.deb

- name: enable gridengine commands
  lineinfile: dest=/etc/profile.d/zzgridengine.sh line="source /opt/sge/default/common/settings.sh" state=present create=yes
