- name: upload configuration files for qhost
  template: src=exechost.qconf.j2 dest="/tmp/{{item}}.conf"
  with_items: groups.gridengine_clients

- name: add execution hosts
  shell: qconf -de {{item}}; qconf -Ae /tmp/{{item}}.conf
  with_items: groups.gridengine_clients
  changed_when: False
  ignore_errors: yes

- name: add clients as submission hosts
  shell: qconf -as {{item}}
  with_items: groups.gridengine_clients
  changed_when: False
  ignore_errors: yes

- name: add clients as administration hosts
  shell: qconf -ah {{item}}
  with_items: groups.gridengine_clients
  changed_when: False
  ignore_errors: yes

- name: upload configuration file for hostgroups
  template: src={{ item }}.grp.conf.j2 dest=/tmp/{{ item }}.grp.conf
  with_items:
    - "@mallar"
    - "@oldworkstations"
    - "@computenodes"
#    - @cic

- name: add groups
  shell: qconf -dhgrp {{item}}; qconf -Ahgrp /tmp/{{ item }}.grp.conf
  with_items:
    - "@mallar"
    - "@oldworkstations"
    - "@computenodes"
#    - @cic
  changed_when: False
  ignore_errors: yes



#- name: add all hosts to the default queue
#  shell: qconf -aattr queue hostlist {{ item }} comp.q
#  with_items:
#    - @mallar
#    - @oldworkstations
#    - @computenodes
#  ignore_errors: yes
#  changed_when: False

- name: fetch list of users
  shell: 'ypcat passwd | cut -d : -f 1'
  register: gridengine_users
  changed_when: False

- name: register managers
  shell: qconf -am {{gridengine_users.stdout}}
  ignore_errors: yes
  changed_when: False

- name: register operators users
  shell: qconf -ao {{gridengine_users.stdout}}
  ignore_errors: yes
  changed_when: False
